---
abstract: 'Module to validate and format Danish telephonenumbers'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Data::FormValidator: '0'
  Taint::Runtime: '0'
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Prereq::Build: '0'
  Test::Taint: '0'
  perl: v5.8.0
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-DK-Phonenumber
provides:
  Business::DK::Phonenumber:
    file: lib/Business/DK/Phonenumber.pm
    version: '0.08'
  Class::Business::DK::Phonenumber:
    file: lib/Class/Business/DK/Phonenumber.pm
    version: '0.08'
  Data::FormValidator::Constraints::Business::DK::Phonenumber:
    file: lib/Data/FormValidator/Constraints/Business/DK/Phonenumber.pm
    version: '0.08'
requires:
  Carp: '0'
  Exporter: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-Phonenumber
  homepage: http://logicLAB.jira.com/browse/BDKPHN
  license: http://www.perlfoundation.org/artistic_license_1_0
  projectChangelog: http://logiclab.jira.com/browse/BDKPHN#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  projectSite: http://logicLAB.jira.com/browse/BDKPHN
  projectWiki: http://logiclab.jira.com/wiki/display/BDKPHN/Home
  repository: https://github.com/jonasbn/bdkphn
version: '0.08'
