---
abstract: 'Module to validate and format Danish telephonenumbers'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Data::FormValidator: 0
  Taint::Runtime: 0
  Test::Exception: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
  Test::Taint: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-DK-Phonenumber
provides:
  Business::DK::Phonenumber:
    file: lib/Business/DK/Phonenumber.pm
    version: 0.05
  Class::Business::DK::Phonenumber:
    file: lib/Class/Business/DK/Phonenumber.pm
    version: 0.01
  Data::FormValidator::Constraints::Business::DK::Phonenumber:
    file: lib/Data/FormValidator/Constraints/Business/DK/Phonenumber.pm
    version: 0
requires:
  Carp: 0
  Exporter: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-DK-Phonenumber
  homepage: http://logicLAB.jira.com/browse/BDKPHN
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BDKPHN
version: 0.05
